Controllers done
JakuninOleg/TestGuru pull request #10
Opened 2018-03-03 00:40 UTC by JakuninOleg

2018-03-03 14:57 UTC, iBublik requested changes

2018-03-03 14:57 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    question = Question.create(body: question_params[:body], test_id: params[:test_id])
1. Смысл PermittedParams как раз в том, чтоб создать список разрешенных параметров, а потом без страха передавать их в модель - `Question.new(question_params)`. 
2. Чтоб привязать вопрос к тесту, лучше использовать ассоциации (так мы скрываем детали реализации связей) - `test.questions.build`

2018-03-03 14:57 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(question.test)
С точки зрения UX стоит вывести сообщение, чтоб пользователь понимал, что его действие не прошло бесследно

2018-03-03 14:57 UTC, iBublik commented on config/routes.rb
> +  resources :tests do
Здесь стоит указать опцию `shallow: true` - это позволит удалять, редактировать и показывать вложенные ресурсы без указания родительсого id в маршрутах. Сильно упрощает роутинг

2018-03-04 01:39 UTC, JakuninOleg commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(question.test)
По идее тут идёт редирект на тест со списком вопросов и мы видим новый вопрос в списке. Но есть идея добавить flash на страницу

2018-03-04 05:43 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    if question.save
У тебя `create` уже делает сохранение в базу. И ты пытаешься его еще раз сделать - это избыточно. Лучше сначала простой создай вопрос в памяти (`new`), а потом его сохраняй

2018-03-04 05:43 UTC, iBublik commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(question.test)
А представь, что у тебя там много вопросов. Неудобно же выискивать среди них тот, что ты удалял.
Так же, возможно тут когда-нибудь будет пагинация. И если ты удалил вопрос со второй страницы, то пользователю придется проверить несколько страниц, чтоб удостовериться что вопрос удален.
В общем, пожалей пользователя :)

2018-03-04 12:33 UTC, JakuninOleg commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(question.test)
Ой, я перепутал с методом create. Но тут тот же принцип про удаление - мы сразу видим что вопрос в списке пропадает после того как нажимаем на кнопку удаления. Про мультистраничность - хорошее замечание, тут, наверное, нужен редирект на страницу с которой удаляес. Но флэш я на удаление тоже добавил теперь.

2018-03-04 18:41 UTC, psylone approved these changes

2018-03-04 18:41 UTC, psylone commented on config/routes.rb
> +  resources :tests, shallow: true do
Опция `shallow` должна бтыь у ресурса вопросов.

2018-03-04 18:41 UTC, psylone commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(question.test)
> Но тут тот же принцип про удаление - мы сразу видим что вопрос в списке пропадает после того как нажимаем на кнопку удаления.

Если вопросов 10-20, то да. Если больше или пагинация, то нет. Так или иначе обратная связь от UI должна быть.

2018-03-04 18:41 UTC, psylone commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(question.test)
`redirect_to question.test`.

2018-03-04 21:43 UTC, merged