Views, helpers are done
JakuninOleg/TestGuru pull request #11
Opened 2018-03-05 22:06 UTC by JakuninOleg

2018-03-06 16:26 UTC, iBublik requested changes

2018-03-06 16:26 UTC, iBublik commented on app/helpers/questions_helper.rb
> +      "Создайте новый вопрос для теста #{@test.title}"
Хелперы не должны опираться на неявное состояние (непонятно откуда взявшаяся инстанс-переменная). Проще всего изначально создавать вопрос привязанным к тесту, тогда текущих параметров будет достаточно

2018-03-06 16:26 UTC, iBublik commented on app/views/questions/_form.html.erb
> +  <%= form_with model: [@test, @question], local: true do |form| %>
Партиалы предполагают переиспользование, поэтому все переменные в них надо передавать явно. Инача потом никто не разберет, откуда вообще данные приходят

2018-03-06 16:26 UTC, iBublik commented on app/views/shared/_back.html.erb
> +     <%= link_to 'Назад', 'javascript:history.go(-1)' %>
А чем `link_to_back` не угодил?

2018-03-06 16:26 UTC, iBublik commented on app/views/shared/_footer.html.erb
> +      'https://thinknetica.com' %><br />
Эта ссылка должна открываться в новом окне

2018-03-06 22:32 UTC, JakuninOleg commented on app/views/shared/_back.html.erb
> +     <%= link_to 'Назад', 'javascript:history.go(-1)' %>
Данный вариант работает как стрелочка назад в браузере. Пробовал link_to :back и request.referrer, но эти методы возвращают на предыдущую страницу, то есть кнопка назад будет нас кидать между двумя страницами.

2018-03-07 00:11 UTC, JakuninOleg commented on app/views/questions/_form.html.erb
> +  <%= form_with model: [@test, @question], local: true do |form| %>
А у нас в задании указано -  применить метод в таком виде form_with model: [@parent, @child]. Как здесь исправить можно?

2018-03-07 00:14 UTC, JakuninOleg commented on app/views/questions/_form.html.erb
> +  <%= form_with model: [@test, @question], local: true do |form| %>
И у нас этот партиал ведь сделан конкретно для формы создания/редактирования вопроса и более нигде не будет задействован

2018-03-08 07:11 UTC, psylone approved these changes

2018-03-08 07:11 UTC, psylone commented on app/helpers/questions_helper.rb
> +  def question_header(test)
У нас же `question_header`, поэтому стоит передавать объект `question`.

2018-03-08 07:11 UTC, psylone commented on app/helpers/questions_helper.rb
> +    if test.questions.last.new_record?
Это не особенно надежно. Потому что когда пользователь кликнет по ссылке редактировать вопрос, кто-то другой в этот момент может создать новый вопрос и здесь `last` уже будет не то что нужно первому пользователю.

Стоит передавать объект вопроса в параметре.

2018-03-08 07:11 UTC, psylone commented on app/views/questions/_form.html.erb
> +  <%= form_with model: [@test, @question], local: true do |form| %>
> Партиалы предполагают переиспользование, поэтому все переменные в них надо передавать явно. Инача потом никто не разберет, откуда вообще данные приходят

Верно, но если мы точно знаем что фрагмент представления не будет шарится, можно вполне обойтись инстанс-переменными внутри фрагмента. Опять же, с другой стороны, проще тестировать фрагмент если данные находятся за его пределом (передаются через локальные переменные). Но поскольку мы вряд ли будем отдельно тестировать фрагмент который используется в конкретном шаблоне то можно оставить инстанс-переменные )

Резюмируя, если фрагменты не шарятся между различными шаблонами, их можно воспринимать как `private` методы в Ruby-коде и использовать инстанс переменные внутри этих фрагментов представлений.

2018-03-08 07:11 UTC, psylone commented on app/views/questions/_form.html.erb
> +    <%= form.submit ( form.object.new_record? ? "Создать вопрос" : "Изменить" ),
В будущем это нужно будет вынести в файл локализации (далее по курсу).

2018-03-08 07:11 UTC, psylone commented on app/views/shared/_flash.html.erb
> +<% if flash[:notice] %>
У нас могут быть разные типы флэш-сообщений. Необходимо предусмотреть это поведение и выводить все существующие флэш-сообщения на данный момент.

2018-03-08 18:39 UTC, JakuninOleg commented on app/views/shared/_flash.html.erb
> +<% if flash[:notice] %>
Ок, но у нас пока что только notice есть в приложении, поэтому передал конкретно его

2018-03-08 23:48 UTC, merged