Timer
JakuninOleg/TestGuru pull request #22
Opened 2018-04-16 21:33 UTC by JakuninOleg

2018-04-17 05:48 UTC, iBublik requested changes

2018-04-17 05:48 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +  def time_is_over?
Это явно не логика контроллера, лучше в модели создай метод

2018-04-17 05:48 UTC, iBublik commented on app/models/test.rb
> +  def timer_expired?
Зачем этот метод?

2018-04-17 05:48 UTC, iBublik commented on app/models/test_passage.rb
> +  def terminate!
Это нигде не используется. Хотя после истечения таймера наверняка есть смысл прерывать прохождение теста

2018-04-17 05:48 UTC, iBublik commented on app/models/test_passage.rb
> +    set_timer < Time.now
`Time.current`

2018-04-17 05:48 UTC, iBublik commented on app/models/test_passage.rb
> +  def set_timer
Неудачное название метода. Ты тут ничего не устанавливаешь. Я бы назвал `expires_at`

2018-04-17 05:48 UTC, iBublik commented on app/models/test_passage.rb
> +    created_at + test.timer
У тебя повсюду проверки установлен ли таймер у теста, а тут почему-то нет

2018-04-17 05:48 UTC, iBublik commented on app/models/test_passage.rb
> +  def set_timer
И это явно не публичный метод

2018-04-17 05:48 UTC, iBublik commented on app/views/test_passages/show.html.erb
> +  <%= content_tag :span, '', class: 'timer', data: { timer: @test_passage.test.timer } %>
При перезагрузке страницы таймер запустится снова и будет сбивать пользователя с толку. Нужно выводить реальный остаток времени для прохождения

2018-04-18 11:29 UTC, iBublik commented on app/models/test_passage.rb
> +    expire_at < Time.current if test.timer
`time_left&.positive?`

2018-04-18 12:02 UTC, psylone approved these changes

2018-04-18 12:02 UTC, psylone commented on app/models/test_passage.rb
> +    (expire_at - Time.current).to_i if test.timer
Можно по умолчанию атрибут `timer` ставить в `0` и считать это как тест без таймера, тогда дополнительные проверки здесь будут не нужны.

2018-05-12 08:49 UTC, merged