Done
JakuninOleg/TestGuru pull request #9
Opened 2018-02-26 00:33 UTC by JakuninOleg

2018-02-26 19:02 UTC, iBublik requested changes

2018-02-26 19:02 UTC, iBublik commented on app/models/question.rb
> +    errors.add(:answers, 'Неверное количество ответов') if answers.size != 1..4
Число никогда не может быть равно рейнджу, ведь это разные объекты. Вообще в Rails по умолчанию есть валидация для проверки на длину - `length`

2018-02-26 19:02 UTC, iBublik commented on app/models/test.rb
> +  scope :category, -> (category) { joins(:category).
1. По имени вообще непонятно, что эти скоупы возвращают
2. Скоупы должны быть chainable, т.е. на результат скоупа всегда можно применить другой скоуп или просто запрос. У тебя этот принцип нарушается, т.к. скоуп возвращает массив. Такую логику лучше просто помещать в методы класса
3. Я не понял, какую часть задания ты реализовал этим кодом

2018-02-26 19:02 UTC, iBublik commented on app/models/category.rb
>  class Category < ApplicationRecord
А где же скоуп по умолчанию для категорий?

2018-02-26 19:02 UTC, iBublik commented on app/models/user.rb
> +  scope :passed_tests, -> (user, difficulty) { Test.joins(:test_passages).
Желательно, чтоб скоуп возвращал данные, связанные с классом, в котором он описан. Иначе странно получается - вызываем метод на классе User, а получаем объекты совсем другого класса.
В данном случае лучше было оставить метод экземпляра, его даже использовать было удобнее -  `user.passed_tests(1)` vs `User.passed_tests(user, 1)`

2018-02-26 19:02 UTC, iBublik commented on app/models/user.rb
> +  validates :email, presence: true
Валидации одного типа можно объединять в одну строку - `validates :name, :email, presence: true`

2018-02-26 19:09 UTC, JakuninOleg commented on app/models/question.rb
> +    errors.add(:answers, 'Неверное количество ответов') if answers.size != 1..4
А length нам подойдёт? У нас же проверка на количество ответов, а не на их длину.

2018-02-26 19:11 UTC, JakuninOleg commented on app/models/test.rb
> +  scope :category, -> (category) { joins(:category).
А в задании нужно было переписать метод возвращения категорий используя скоуп, как раз таки. Первый метод возвращает все категории вопросов, второй возвращает вопросы заданной категории.

2018-02-26 19:12 UTC, JakuninOleg commented on app/models/user.rb
> +  scope :passed_tests, -> (user, difficulty) { Test.joins(:test_passages).
Всё верно, просто в задании был пункт переписать методы класса через скоуп - я реализовал это таким образом. Могу перенести это в класс Test.

2018-02-27 04:19 UTC, iBublik commented on app/models/question.rb
> +    errors.add(:answers, 'Неверное количество ответов') if answers.size != 1..4
В Ruby длину массива можно 3 методами узнать - `length`, `size` и `count`

2018-02-27 04:20 UTC, iBublik commented on app/models/user.rb
> +  scope :passed_tests, -> (user, difficulty) { Test.joins(:test_passages).
Так это был метод экземпляра, а не класса

2018-02-27 04:21 UTC, iBublik commented on app/models/test.rb
> +  scope :category, -> (category) { joins(:category).
Я б назвал `with_category_name`, а так непонятно что вообще скоуп делает

2018-02-27 11:54 UTC, psylone requested changes

2018-02-27 11:54 UTC, psylone commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: { scope: :level }
Нужен составной индекс на уникальность.

2018-02-27 11:54 UTC, psylone commented on app/models/test.rb
> +  scope :category, -> (category) { joins(:category).
Или `by_category` )

2018-02-27 11:54 UTC, psylone commented on app/models/test.rb
> -  end
Этот метод стоит оставить, поскольку требуется возвращать **массив** названий.

2018-02-27 11:54 UTC, psylone commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: { scope: :level }
Здесь необходимо добавить составной индекс на уникальность.

2018-02-27 11:54 UTC, psylone commented on app/models/question.rb
> +  validates :answers, length: { in: 1..4 }
Это хорошо, но мы по-прежнему можем созать отдельно ответ, указав у него идентификатор вопроса у которого уже есть 4 ответа и все будет в порядке, хотя не должно.

2018-02-27 11:57 UTC, psylone commented on app/models/user.rb
> -  end
Учитывая, что у нас сейчас нет скоупа для тестов который возвращал бы все тесты для конкретного уровня, этот метод стоило оставить. Со скоупом, можно этот метод действительно удалить и использовать что-то вроде `user.tests.by_level(2)`.

2018-02-28 17:43 UTC, psylone approved these changes

2018-02-28 17:43 UTC, psylone commented on app/models/user.rb
> +    tests.by_level(level).where( test_passages: {user_id: id} )
Последний `where` не нужен, за это условие отвечает ассоциация `tests`.

2018-03-01 20:53 UTC, merged